'use client';

import { useSearchParams } from 'next/navigation';
import { useEffect, useState, useMemo } from 'react';
import Link from 'next/link';
import { ArrowLeft, Download, Share2 } from 'lucide-react';

type Plan = {
  id?: string | null;
  destination: string;
  days: number;
  budget: string;
  overview: string;
};

export default function TripPlanPage() {
  const searchParams = useSearchParams();
  const tripId = searchParams ? searchParams.get('id') : null;
  const [tripPlan, setTripPlan] = useState<Plan | null>(null);
  const [loading, setLoading] = useState(true);

  // Try to hydrate from sessionStorage using tripId, fallback to placeholder
  useEffect(() => {
    setLoading(true);
    const timer = setTimeout(() => {
      let plan: Plan | null = null;

      try {
        const stored = sessionStorage.getItem('currentTripPlan');
        if (stored) {
          const parsed = JSON.parse(stored);
          plan = {
            id: tripId,
            destination: parsed?.tripOverview?.destination || 'Ranchi',
            days: Number((parsed?.tripOverview?.duration || '').replace(/[^\d]/g, '')) || 3,
            budget: parsed?.tripOverview?.totalBudget || '₹25000',
            overview:
              parsed?.tripOverview?.overview ||
              'Your personalized Jharkhand trip plan has been generated!',
          };
        }
      } catch {
        // ignore parse errors, fallback to placeholder
      }

      if (!plan) {
        plan = {
          id: tripId,
          destination: 'Ranchi',
          days: 3,
          budget: '₹25000',
          overview: 'Your personalized Jharkhand trip plan has been generated!',
        };
      }

      setTripPlan(plan);
      setLoading(false);
    }, 400);

    return () => clearTimeout(timer);
  }, [tripId]);

  const share = async () => {
    const url = typeof window !== 'undefined' ? window.location.href : '';
    const title = `${tripPlan?.destination} Trip Plan - PLANORA AI`;
    const text = `Check out my AI-generated trip plan for ${tripPlan?.destination}!`;
    if (navigator.share) {
      try {
        await navigator.share({ title, text, url });
      } catch {
        // user canceled
      }
    } else if (navigator.clipboard && url) {
      await navigator.clipboard.writeText(url);
    }
  };

  const download = () => {
    if (!tripPlan) return;
    const content = `
PLANORA AI - Trip Plan
===================

Destination: ${tripPlan.destination}
Duration: ${tripPlan.days} days
Budget: ${tripPlan.budget}

Overview:
${tripPlan.overview}

Generated by PLANORA AI - Jharkhand Trip Planner
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${tripPlan.destination}-Trip-Plan.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const subtitle = useMemo(
    () => (tripPlan ? `${tripPlan.days} days • ${tripPlan.budget} • Generated by PLANORA AI` : ''),
    [tripPlan]
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gradient-to-br from-green-50 to-blue-50">
        <div className="text-center">
          <div className="w-12 h-12 mx-auto mb-4 border-b-2 border-green-600 rounded-full animate-spin"></div>
          <p className="text-gray-600">Loading your trip plan...</p>
        </div>
      </div>
    );
  }

  if (!tripPlan) {
    return (
      <div className="flex items-center justify-center min-h-screen px-4 bg-gradient-to-br from-green-50 to-blue-50">
        <div className="p-8 text-center border shadow bg-white/80 backdrop-blur rounded-xl">
          <h1 className="mb-3 text-2xl font-bold text-gray-900">Trip Plan Not Found</h1>
          <p className="mb-6 text-gray-600">The trip plan being requested was not found.</p>
          <Link
            href="/"
            className="inline-block px-6 py-3 text-white bg-green-600 rounded-lg hover:bg-green-700"
          >
            Plan a New Trip
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50">
      <div className="max-w-6xl px-4 py-6 mx-auto sm:py-8">
        {/* Header */}
        <div className="flex flex-col items-start justify-between gap-4 mb-6 sm:flex-row sm:items-center sm:mb-8">
          <Link
            href="/"
            className="flex items-center gap-2 text-gray-700 transition-colors hover:text-green-700"
          >
            <ArrowLeft className="w-5 h-5" />
            Back to Home
          </Link>

          <div className="flex gap-2 sm:gap-3">
            <button
              onClick={share}
              className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-500"
            >
              <Share2 className="w-4 h-4" />
              Share
            </button>
            <button
              onClick={download}
              className="flex items-center gap-2 px-4 py-2 text-white bg-green-600 rounded-lg hover:bg-green-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-500"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>

        {/* Trip Plan Content */}
        <div className="p-6 bg-white border border-gray-200 shadow-lg rounded-xl sm:p-8">
          <div className="mb-6 text-center sm:mb-8">
            <h1 className="mb-2 text-2xl font-bold text-gray-900 sm:text-3xl">
              🎉 Your {tripPlan.destination} Trip Plan
            </h1>
            <p className="text-gray-600">{subtitle}</p>
          </div>

          <div className="p-5 mb-8 border border-green-200 rounded-lg bg-green-50 sm:p-6">
            <h2 className="mb-2 text-lg font-semibold text-green-900 sm:text-xl">Trip Overview</h2>
            <p className="text-green-800">{tripPlan.overview}</p>
          </div>

          <div className="grid gap-6 md:grid-cols-2 sm:gap-8">
            <div className="p-5 rounded-lg bg-blue-50 sm:p-6">
              <h3 className="mb-4 text-lg font-semibold text-blue-900">Itinerary Highlights</h3>
              <div className="space-y-3 text-gray-800">
                <div className="flex items-center gap-3">
                  <span className="flex items-center justify-center w-6 h-6 text-sm text-white bg-blue-600 rounded-full">
                    1
                  </span>
                  <span>Arrival & Hundru Falls visit</span>
                </div>
                <div className="flex items-center gap-3">
                  <span className="flex items-center justify-center w-6 h-6 text-sm text-white bg-blue-600 rounded-full">
                    2
                  </span>
                  <span>Rock Garden & Tagore Hill exploration</span>
                </div>
                <div className="flex items-center gap-3">
                  <span className="flex items-center justify-center w-6 h-6 text-sm text-white bg-blue-600 rounded-full">
                    3
                  </span>
                  <span>Dassam Falls & departure</span>
                </div>
              </div>
            </div>

            <div className="p-5 rounded-lg bg-orange-50 sm:p-6">
              <h3 className="mb-4 text-lg font-semibold text-orange-900">Budget Breakdown</h3>
              <div className="space-y-2 text-gray-800">
                <Row k="Accommodation" v="₹10,000" />
                <Row k="Food & Dining" v="₹6,250" />
                <Row k="Transportation" v="₹5,000" />
                <Row k="Activities" v="₹2,500" />
                <div className="flex justify-between pt-2 font-bold border-t">
                  <span>Total:</span>
                  <span className="text-green-600">₹25,000</span>
                </div>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="mt-8 text-center">
            <p className="mb-4 text-gray-600">Need to modify your plan or have questions?</p>
            <div className="flex flex-col justify-center gap-3 sm:flex-row sm:gap-4">
              <Link
                href="/chat?context=trip-details"
                className="px-6 py-3 text-center text-white bg-blue-600 rounded-lg hover:bg-blue-700"
                onClick={() => {
                  try {
                    // hand off trip plan to chat
                    sessionStorage.setItem(
                      'currentTripPlan',
                      JSON.stringify({
                        tripOverview: {
                          destination: tripPlan.destination,
                          duration: `${tripPlan.days} days`,
                          totalBudget: tripPlan.budget,
                          overview: tripPlan.overview,
                        },
                      })
                    );
                  } catch {}
                }}
              >
                Chat with AI
              </Link>
              <Link
                href="/"
                className="px-6 py-3 text-center bg-white border border-gray-300 rounded-lg hover:bg-gray-50"
              >
                Plan Another Trip
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex justify-between">
      <span>{k}:</span>
      <span className="font-medium">{v}</span>
    </div>
  );
}
